language: node_js

node_js:
  - '10'

sudo: false

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - node_modules

script:
  - yarn eslint
  - yarn test

before_deloy:
  - yarn dist
  - npm version $TRAVIS_TAG

deploy:
  provider: npm
  email: "contact@yoctu.com"
  api_key:
    secure: ZpxRIQh7NGkLSXJwevOzKdsA0S898O+51zClNUAA4hBdXXuIVxnslXywPz5HVQElEVTaCocO4H1YcRz1hVbgz8CeVsNkfX+GWWcUy73eebaw9Gs0qiYQBW0MB4TGCpdmgyCWs9gBAVX8HpZPvv2tkBiJZl3IrPB3mVb6JyUj44p0szUis7YRRIKOIdUT2zTe6H4PD4CG3OawjyGiSrMMi1XV48iXnxV/hv0Rl0ib+IolaDqHd5qB+G2BoJ8tYLylJcqmoZ7H4o7vnnTxfflJTwuxUp4sccteX++HBeOwcf7l1MTLcK7nssl2g+VzHtpZsjgkAY+L8qKTFMivN7dDPVHWiUkee0P0dnANGxgtv9GZjFksQCoouSKqccCc9d7BS9HpwjaJOvyh3EG0yJdL7PqlIhEqVdymYzu5TWf5uFJQhDK9y1hHMJuxYDDu+1cZaT/+ADGs0EwRkscPdXjR2P7vSXYM1PCl+DEHKJ6Fe0NQdm3kv16nUhfmGh9deP3XzPLfSAjDBN8NEVzoyR9nzwb4FyRBpsP/SOdJT7QK2ertaFA6en9sGZQhhGUemLzMDuTRqrQZllfl87kpg+c7g47T3HfvjogiHColDJagRVTe7AIn90ONiNmPnuTXF95UUilOnt2aEzUZqSSMWFYbazwOBt6ESIvrvy8l2s1BW8c=
  on:
    tags: true
